
import { Component, ElementRef, ViewChild, output, signal } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-tos-modal',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-slate-950/90 backdrop-blur-md animate-fade-in">
      <div class="bg-slate-900 border border-slate-700 rounded-2xl w-full max-w-lg shadow-2xl flex flex-col max-h-[85vh]">
        
        <div class="p-6 border-b border-slate-800">
          <h2 class="text-2xl font-bold text-white font-tech">Terms of Service</h2>
          <p class="text-xs text-slate-400">Please read carefully to proceed.</p>
        </div>

        <div #scrollContainer 
             (scroll)="onScroll()"
             class="flex-1 overflow-y-auto p-6 space-y-4 text-sm text-slate-300 leading-relaxed custom-scroll">
          
          <p class="font-bold text-white">1. Introduction</p>
          <p>Welcome to DemoMax. By accessing this platform, you agree to abide by these Terms of Service. This is an AI-driven roleplay environment intended for users 18+.</p>

          <p class="font-bold text-white">2. Age Restriction (18+)</p>
          <p>You strictly confirm that you are at least 18 years of age. Access by minors is prohibited. We employ content filtering, but you are responsible for your interactions.</p>

          <p class="font-bold text-white">3. User Conduct (Zero Tolerance)</p>
          <p>Users are prohibited from generating content related to:</p>
          <ul class="list-disc pl-5 space-y-1">
            <li>Child sexual abuse material (CSAM) or exploitation of minors.</li>
            <li>Non-consensual sexual content (deepfakes of real people).</li>
            <li>Promotion of self-harm, suicide, or violence.</li>
          </ul>
          <p>Violations result in immediate bans and reporting to authorities where applicable.</p>

          <p class="font-bold text-white">4. Virtual Economy</p>
          <p>"Sakura Coins" and items have no real-world monetary value. They cannot be exchanged for cash. Transactions are final.</p>

          <p class="font-bold text-white">5. AI Content Disclaimer</p>
          <p>Characters are generated by AI. They may produce unpredictable outputs. DemoMax is not responsible for the opinions or "hallucinations" of AI agents.</p>

          <p class="font-bold text-white">6. Privacy Policy</p>
          <p>We process data to provide AI services. Conversations may be processed by third-party LLM providers (e.g., Google Gemini) solely for generation purposes.</p>

          <p class="font-bold text-white">7. Termination</p>
          <p>We reserve the right to terminate accounts without notice for TOS violations.</p>
          
          <div class="h-12"></div> <!-- Spacer -->
          <div class="text-center text-xs text-slate-500 italic">End of Document</div>
        </div>

        <div class="p-6 border-t border-slate-800 bg-slate-900/50">
           <div class="flex items-center gap-3 mb-4">
              <input type="checkbox" 
                     id="agree" 
                     [disabled]="!hasScrolledToBottom()"
                     [(checked)]="isChecked"
                     (change)="toggleCheck($event)"
                     class="w-5 h-5 rounded border-slate-600 text-pink-600 focus:ring-pink-500 disabled:opacity-50">
              <label for="agree" class="text-sm select-none" [class.text-slate-500]="!hasScrolledToBottom()" [class.text-white]="hasScrolledToBottom()">
                 I have read and agree to the Terms of Service.
              </label>
           </div>
           
           <button (click)="confirm.emit()" 
                   [disabled]="!isChecked || !hasScrolledToBottom()"
                   class="w-full py-3 rounded-xl bg-gradient-to-r from-pink-600 to-violet-600 text-white font-bold disabled:opacity-50 disabled:cursor-not-allowed transition-all">
              Accept & Continue
           </button>
        </div>

      </div>
    </div>
  `,
  styles: [`
    .animate-fade-in { animation: fadeIn 0.3s ease-out; }
    @keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }
  `]
})
export class TosModalComponent {
  confirm = output();
  
  @ViewChild('scrollContainer') scrollContainer!: ElementRef;
  
  hasScrolledToBottom = signal(false);
  isChecked = false;

  onScroll() {
    const el = this.scrollContainer.nativeElement;
    // Allow a small buffer (e.g. 10px) for float calculation errors
    const isBottom = el.scrollHeight - el.scrollTop - el.clientHeight < 50;
    
    if (isBottom) {
      this.hasScrolledToBottom.set(true);
    }
  }

  toggleCheck(event: Event) {
    const input = event.target as HTMLInputElement;
    this.isChecked = input.checked;
  }
}
